#!/usr/bin/env bash

query="$(rofi -dmenu -p 'Search >')"

# If query matches an installed desktop app, run it
match=$(compgen -c | grep -i "^$query" | head -n 1)

if [ -n "$match" ]; then
    exec "$match"
else
    exec thorium-browser "https://www.google.com/search?q=${query// /+}"
fi

