#!/usr/bin/env bash
set -euo pipefail

# make sure hyprpaper is running
if ! pgrep -x "hyprpaper" > /dev/null; then
    nohup hyprpaper >/dev/null 2>&1 & 
    sleep 2
fi

WALLPAPER_DIR="$HOME/.wallpapers"

# Pick category via rofi
category=$(ls "$WALLPAPER_DIR" | rofi -dmenu -p "Pick theme")
if [ -z "$category" ]; then
    echo "No category selected, exiting."
    exit 0
fi
echo "Category: $category"

# Get focused monitor + resolution
monitor=$(hyprctl monitors -j | jq -r '.[] | select(.focused==true).name')
width=$(hyprctl monitors -j | jq -r '.[] | select(.focused==true).width')
height=$(hyprctl monitors -j | jq -r '.[] | select(.focused==true).height')

echo "Monitor: $monitor"
echo "Resolution: ${width}x${height}"

# Orientation
orient="h"
[ "$height" -gt "$width" ] && orient="v"
echo "Orientation: $orient"

# Pick random wallpaper
if [ "$category" != "center" ]; then
  folder="$WALLPAPER_DIR/$category/$orient"
else
  folder="$WALLPAPER_DIR/$category"
fi

if [ ! -d "$folder" ]; then
    echo "ERROR: Folder $folder does not exist."
    exit 1
fi

wallpaper=$(find "$folder" -type f | shuf -n 1)
if [ -z "$wallpaper" ]; then
    notify-send "ERROR: No wallpapers found in $folder."
    exit 1
fi
echo "Selected wallpaper: $wallpaper"

if [ "$category" = "center" ]; then
    echo "Center wallpaper..."
    bgcolor=$(magick "$wallpaper" -format "%[pixel:p{2,2}]" info:)

    echo "bgcolor: $bgcolor"

    # resize it to fit screen - taking into account the monitor rotation.
    if [ "$orient" = "h" ]; then
        height="$height"
        width="$width"
    else
        height="$width"
        width="$height"
    fi

    maxw=$(( width * 60 / 100 ))
    maxh=$(( height * 60 / 100 ))

    echo "Resizing wallpaper to ${maxw}x${maxh}..."

    magick "$wallpaper" -resize "${maxw}> " /tmp/wpmod.png
    wallpaper="/tmp/wpmod.png"
    magick "$wallpaper" -resize "x${maxh}> " /tmp/wpmod.png

    magick -size ${width}x${height} xc:"$bgcolor" \
        /tmp/wpmod.png -gravity center -composite \
        "/tmp/wallpaper.png"

    rm /home/jrk/.cache/wal/schemes/_tmp_wallpaper_png*

    wallpaper=/tmp/wallpaper.png
fi

# Set wallpaper
echo "Preloading wallpaper..."

hyprctl hyprpaper unload all

if ! hyprctl hyprpaper preload "$wallpaper"; then
    echo "ERROR: preload failed."
    exit 1
fi

echo "Applying wallpaper to $monitor..."
if ! hyprctl hyprpaper wallpaper "$monitor,$wallpaper"; then
    echo "ERROR: wallpaper command failed."
    exit 1
fi

# pywal set colors from wall paper:
if command -v wal >/dev/null 2>&1; then
    wal -i "$wallpaper"

    # Reload waybar
    if command -v waybar >/dev/null 2>&1; then
        pkill waybar
        waybar &
    fi


fi

echo "Done."
