#!/bin/bash

PID_FILE="/tmp/hypr_wp_DP-1.pid"
if [[ -f "$PID_FILE" ]] then
  kill $(cat "$PID_FILE") 2>/dev/null
  rm "$PID_FILE"
fi

PID_FILE="/tmp/hypr_wp_HDMI-A-1.pid"
if [[ -f "$PID_FILE" ]] then
  kill $(cat "$PID_FILE") 2>/dev/null
  rm "$PID_FILE"
fi

PID_FILE="/tmp/hypr_wp_DVI-D-1.pid"
if [[ -f "$PID_FILE" ]] then
  kill $(cat "$PID_FILE") 2>/dev/null
  rm "$PID_FILE"
fi
