#!/usr/bin/env bash

WS=$(hyprctl -j activeworkspace | jq -r '.id')

case "$WS" in
  12) exec filezilla ;;
  13) exec kitty -d /srv/http ;;
  14) exec firefox ;;
  19) exec Telegram ;;
  *) exec rofi -show combi -modes combi -combi-modes "window,drun"
esac
