/* Generated by pywal */

* {
    bg: rgb({background.rgb});
    fg: rgb({foreground.rgb});
    color0: rgb({color0.rgb});
    color1: rgb({color1.rgb});
    color2: rgb({color2.rgb});
    color3: rgb({color3.rgb});
    color4: rgb({color4.rgb});
    color5: rgb({color5.rgb});
    color6: rgb({color6.rgb});
    color7: rgb({color7.rgb});
    color8: rgb({color8.rgb});
    color9: rgb({color9.rgb});
    color10: rgb({color10.rgb});
    color11: rgb({color11.rgb});
    color12: rgb({color12.rgb});
    color13: rgb({color13.rgb});
    color14: rgb({color14.rgb});
    color15: rgb({color15.rgb});

    font: "JetBrainsMono Nerd Font 12";
}


window {
    transparency: "real";
    background-color: rgba({background.rgb}, 0.85);
    border: 2px;
    border-color: @color4;
    padding: 20px;
    width: 40%;
}

mainbox {
    spacing: 10px;
}

inputbar {
    background-color: rgba({color0.rgb}, 0.6);
    padding: 8px;
    border-radius: 6px;
}

prompt {
    text-color: @color4;
}

entry {
    text-color: @fg;
}

listview {
    spacing: 6px;
    scrollbar: false;
}

element {
    padding: 6px;
    border-radius: 4px;
}

element-text {
    text-color: @fg;
}

element selected {
    background-color: rgba({color4.rgb}, 0.35);
}

element-text selected {
    text-color: @color4;
}

