#!/bin/sh

alias krc='cd ~/.config/kitty && nvim ~/.config/kitty/kitty.conf'
alias zrc='cd ~ && nvim ~/.zshrc'
alias vrc='cd ~ && nvim ~/.vimrc'
alias nrc='cd ~/.config/nvim && nvim ~/.config/nvim/init.lua'
alias hrc='cd ~/.config/hypr && nvim ~/.config/hypr/hyprland.conf'
alias arc='cd ~/.config/awesome && nvim ~/.config/awesome/rc.lua'
