# Fuck Off With Your Shit - WTF!?!?  Who Wants This!?!
splash = false

$monitor1 = DVI-D-1
$monitor2 = DP-1
$monitor3 = HDMI-A-1

$wp1 = ~/.wallpapers/safe/v/wp9203593.jpg
$wp2 = ~/.wallpapers/safe/h/wood-2.jpg
$wp3 = ~/.wallpapers/safe/h/wood-2.jpg


preload = $wp1
preload = $wp2
preload = $wp3

wallpaper = $monitor1,$wp1
wallpaper = $monitor2,$wp2
wallpaper = $monitor3,$wp3
